### ISSUE TITLE
Missing out of bounds check

### ISSUE THREAD

**Issue by orangecms** [linuxboot/fiano#337]
This here may crash at runtime:

https://github.com/linuxboot/fiano/blob/11c2c1a9fd46d33d2e4b21901a3a48fdda1e31a4/pkg/uefi/firmwarevolume.go#L257

Check if `fv.Length` is really in range of `data`.

see also https://github.com/fiedka/fiedka/issues/50

**Comment by orangecms** [comment]
The odd part is that there is already a check:
https://github.com/linuxboot/fiano/blob/11c2c1a9fd46d33d2e4b21901a3a48fdda1e31a4/pkg/uefi/firmwarevolume.go#L231

needs some more thorough investigation

**Comment by GanShun** [comment]
So I note that fiedka was pulling down v5.0.0 due to go modules, can you check again with the latest v1.0.1? I think v5.0.0 predated the checks

**Comment by orangecms** [comment]
Yea the version stuff was a mess... closing this now. :)
